name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v

    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.21

    - name: Build and Test
      run: |
        go build ./...
        go test ./...
